name: deploy for main

on:
  push: # 推送到主分支，合并PR的时候，会触发。主分支不能直接push, 所以这里必然是PR合并触发的。
    branches:
      - 'main' # 只针对 main 分支
    paths: # 触发的文件路径
      - '.github/workflows/*'
      - 'src/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true # 加个判断，当前的操作是PR合并才会处理
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: borales/actions-yarn@v2.3.0
          with:
            cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.3.0
          with:
            cmd: test # will run `yarn test` command
      - uses: borales/actions-yarn@v2.3.0
          with:
            cmd: build # will run `yarn build` command
      - name: deploy # 部署
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY_ALI }}
          ARGS: "-avz --delete"
          SOURCE: "build/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST_ALI }}
          REMOTE_USER: ${{ secrets.REMOTE_USER_ALI }}
          TARGET: ${{ secrets.REMOTE_TARGET_ALI }}
