name: test todo

on:
  pull_request: # 提交PR的时候会触发
    branches:
      - main # 触发分支为 main 分支
    paths:
      - '.github/workflows/**'
      - 'src/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: borales/actions-yarn@v2.3.0
          with:
            cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.3.0
          with:
            cmd: test # will run `yarn test` command
